version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - VERSION=docker
    volumes:
      - M:/Configs/plex:/config
      - M:/TV Shows:/data/tvshows
      - M:/Movies:/data/movies
      - M:/Transcode:/transcode
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
    restart: unless-stopped

  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/hydra2:/config
      - M:/Downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/nzbget:/config
      - M:/Downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/sonarr:/config
      - M:/TV Shows:/tv
      - M:/Downloads:/downloads
    ports:
      - 8989:8989
    links:
      - plex
      - hydra2
      - nzbget
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/radarr:/config
      - M:/Movies:/movies
      - M:/Downloads:/downloads
    ports:
      - 7878:7878
    links:
      - plex
      - hydra2
      - nzbget
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/ombi:/config
    ports:
      - 3579:3579
    links:
      - plex
      - sonarr
      - radarr
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/tautulli:/config
      - M:/Configs/plex/Library/Application Support/Plex Media Server/Logs
    ports:
      - 8181:8181
    links:
      - plex
    restart: unless-stopped

  nginx:
    image: linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - M:/Configs/nginx:/config
    ports:
      - 80:80
      - 443:443
    links:
      - plex
      - hydra2
      - nzbget
      - sonarr
      - radarr
      - ombi
      - tautulli
    restart: unless-stopped
