version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
    volumes:
      - /var/data/config/plex:/config
      - /var/data/media/tv:/tv
      - /var/data/media/movies:/movies
    ports:
      - 32469:32469
      - 32400:32400
      - 32401:32401
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - internal
  radarr:
    image: lscr.io/linuxserver/radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/radarr:/config
      - /var/data/media/movies:/movies
      - /var/data/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - internal
  sonarr:
    image: lscr.io/linuxserver/sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/sonarr:/config
      - /var/data/media/tv:/tv
      - /var/data/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - internal
  nzbget:
    image: lscr.io/linuxserver/nzbget
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nzbget:/config
      - /var/data/downloads:/downloads
    ports:
      - 6789:6789
    networks:
      - internal
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nzbhydra2:/config
      - /var/data/downloads:/downloads
    ports:
      - 5076:5076
    networks:
      - internal
  ombi:
    image: lscr.io/linuxserver/ombi
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/ombi:/config
    ports:
      - 3579:3579
    networks:
      - internal
  tautulli:
    image: lscr.io/linuxserver/tautulli
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/tautulli:/config
    ports:
      - 8181:8181
    networks:
      - internal
  nginx:
    image: lscr.io/linuxserver/nginx
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nginx:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
networks:
  # The presence of these objects is sufficient to define them
  internal: {}
