version: '2.1'
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - VERSION=docker
    volumes:
      - /var/data/config/plex:/config
      - /var/data/media/tv:/tv
      - /var/data/media/movies:/movies
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/radarr:/config
      - /var/data/media/movies:/movies
	  - /var/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/sonarr:/config
      - /var/data/media/tv:/tv
	  - /var/data/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nzbget:/config
	  - /var/data/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  nzbhydra2:
    image: lscr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nzbhydra2:/config
      - /var/data/downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Australia/Sydney
    volumes:
      - /var/data/config/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
